remote_theme: zerostaticthemes/jekyll-serif-theme
plugins:
  - jekyll-remote-theme

title: Weather API Docs
description: Sample API documentation project using Redoc
url: "https://bunchhaus.github.io"
baseurl: "/weather-api-docs"


