openapi: 3.0.0
info:
  title: Weather API
  version: 1.0.0

servers:
  - url: https://api.example.com/v1
    description: Production server

paths:
  /current:
    get:
      summary: Get current weather
      parameters:
        - in: query
          name: city
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentWeather'
              example:
                coord:
                  lon: -73.9496
                  lat: 40.6501
                weather:
                  - id: 721
                    main: Haze
                    description: haze
                    icon: "50d"
                base: stations
                main:
                  temp: 28.79
                  feels_like: 30.26
                  temp_min: 27.14
                  temp_max: 30.06
                  pressure: 1025
                  humidity: 57
                  sea_level: 1025
                  grnd_level: 1025
                visibility: 8047
                wind:
                  speed: 6.17
                  deg: 120
                clouds:
                  all: 40
                dt: 1754414061
                sys:
                  type: 2
                  id: 2080536
                  country: US
                  sunrise: 1754387799
                  sunset: 1754438812
                timezone: -14400
                id: 5110302
                name: Brooklyn
                cod: 200

  /forecast:
    get:
      summary: Get 5-day weather forecast
      parameters:
        - in: query
          name: city
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forecast'
              example:
                days:
                  - date: "2025-08-05"
                    temperature: 28.5
                    condition: "Haze"
                  - date: "2025-08-06"
                    temperature: 27.3
                    condition: "Partly Cloudy"
                  - date: "2025-08-07"
                    temperature: 29.1
                    condition: "Sunny"
                  - date: "2025-08-08"
                    temperature: 30.0
                    condition: "Thunderstorms"
                  - date: "2025-08-09"
                    temperature: 26.8
                    condition: "Rain"

components:
  schemas:
    CurrentWeather:
      type: object
      properties:
        coord:
          type: object
          properties:
            lon:
              type: number
            lat:
              type: number
        weather:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              main:
                type: string
              description:
                type: string
              icon:
                type: string
        base:
          type: string
        main:
          type: object
          properties:
            temp:
              type: number
            feels_like:
              type: number
            temp_min:
              type: number
            temp_max:
              type: number
            pressure:
              type: integer
            humidity:
              type: integer
            sea_level:
              type: integer
            grnd_level:
              type: integer
        visibility:
          type: integer
        wind:
          type: object
          properties:
            speed:
              type: number
            deg:
              type: integer
        clouds:
          type: object
          properties:
            all:
              type: integer
        dt:
          type: integer
        sys:
          type: object
          properties:
            type:
              type: integer
            id:
              type: integer
            country:
              type: string
            sunrise:
              type: integer
            sunset:
              type: integer
        timezone:
          type: integer
        id:
          type: integer
        name:
          type: string
        cod:
          type: integer
    Forecast:
      type: object
      properties:
        days:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date
              temperature:
                type: number
              condition:
                type: string

